name: cash-manager-pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: GOOS=linux GOARCH=amd64 go test -v

      - name: Go vet
        run: |
          go vet ./...
